name: Release
on:
  workflow_dispatch:
jobs:
  package:
    uses: ./.github/workflows/reusable-package.yml
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: |
          tag=$(gh release view -R ryanoasis/nerd-fonts --json tagName -q '.tagName')
          gh release create "${tag}" --notes "JetBrainsMono Nerd Font ${tag}" ./build/*.msi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
