name: Reusable package
on:
  workflow_call:
jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        shell: pwsh
        run: choco install pandoc
      - name: Build package
        shell: pwsh
        run: ./src/Build-Installer.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: src/bin/Release/en-US/*.msi
          if-no-files-found: error
