name: Reusable package
on:
  workflow_call:
jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          (gh release view -R ryanoasis/nerd-fonts --json assets) -match '(?<url>https://[^"]+?JetBrainsMono\.zip)"'
          $asset = $Matches.url

          Invoke-WebRequest -Uri $asset -OutFile $PSScriptRoot\JetBrainsMono.zip
          Remove-Item `
              -Path $PSScriptRoot\JetBrainsMonoNF\Fonts `
              -Recurse `
              -Force `
              -ErrorAction SilentlyContinue
          New-Item `
              -Path $PSScriptRoot\JetBrainsMonoNF\Fonts `
              -ItemType Directory
          Expand-Archive `
              -Path $PSScriptRoot\JetBrainsMono.zip `
              -DestinationPath $PSScriptRoot\JetBrainsMonoNF\Fonts `
              -Force
          Remove-Item `
              -Path $PSScriptRoot\JetBrainsMonoNF\Fonts\* `
              -Exclude *Windows*

          $asset -match '/v(?<version>[\d.]+)/'
          $version = $Matches.version

          (Get-Content -Path $PSScriptRoot\JetBrainsMonoNF\Product.xml) `
              -creplace '(\bVersion=)"[\d.]+"', ('$1"' + $version + '"') `
              > $PSScriptRoot\JetBrainsMonoNF\Product.wxs

          msbuild /p:Configuration=Release `
              $PSScriptRoot\JetBrainsMonoNF\JetBrainsMonoNF.wixproj
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: JetBrainsMonoNF/bin/Release/*.msi
          if-no-files-found: error
