name: Reusable package
on:
  workflow_call:
jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: Install WiX v4
        shell: pwsh
        run: dotnet tool install --global wix
      - uses: actions/checkout@v3
      - name: Build package
        shell: pwsh
        run: ./src/Build-Installer.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: src/bin/Release/en-US/*.msi
          if-no-files-found: error
